apiVersion: apps/v1
#Using deployment resource to make sure one db replica always available
kind: Deployment
metadata:
  name: mediawiki-db
spec:
  selector:
    matchLabels:
      app: mediawiki-db
  # creates one replica
  replicas: 1
  template:
    metadata:
      labels:
        app: mediawiki-db
    spec:
      containers:
        - name: mediawiki-db-container
          # will fetch maridb from docker container
          image: mariadb
          ports:
            # Exposing port which is also the default port
            - containerPort: 3306
              name: db-port
          env:
            # Below env variable will create the diffrent user name and password for db
            - name: MYSQL_DATABASE
              value: my_wiki
            - name: MYSQL_USER
              value: wikiuser
            - name: MYSQL_PASSWORD
              value: example
            - name: MYSQL_ROOT_PASSWORD
              value: my-password
