---
apiVersion: v1
kind: Pod
metadata:
  name: pod-a
spec:
  containers:
  - name: mediawiki-container
    image: mediawiki
    volumeMounts:
      - mountPath: /var/www/html/images
        name: mediawiki-volume
    ports:
      - containerPort: 80
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "400Mi"
  volumes:
    - name: mediawiki-volume

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-b
spec:
  containers:
  - name: mediawiki-container
    image: mediawiki
    volumeMounts:
      - mountPath: /var/www/html/images
        name: mediawiki-volume
    ports:
      - containerPort: 80
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi"
  volumes:
    - name: mediawiki-volume

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-c
spec:
  containers:
  - name: mediawiki-container
    image: mediawiki
    volumeMounts:
      - mountPath: /var/www/html/images
        name: mediawiki-volume
    ports:
      - containerPort: 80
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "400Mi"
  volumes:
    - name: mediawiki-volume
